export default {
  LOGIN_ROUTE: "/login",
  LOGOUT_ROUTE: "/logout",
  FORGOT_PASSWORD: "/Forgotpassword",
  RESET_PASSWORD: "/password/reset/:id",
  UPDATE_PASSWORD: "/updatePassword/:id",
  USERS_ROUTE: "users",
  USER_ID_ROUTE: "user/:id",
  EDIT_USER_ID: "user/edit/:id",
  PRODUCTS_ROUTE: "products",
  PRODUCT_ID_ROUTE: "product/:id",
  EDIT_PRODUCT_ID: "product/edit/:id",
  TRANSACTIONS_ROUTE: "transactions",
  TRANSACTION_ID_ROUTE: "transaction/:id",
  EDIT_TRANSACTION_ID: "transaction/edit/:id",
  COMMENTS_ROUTE: "comments",
  COMMENT_ID_ROUTE: "comment/:id",
  EDIT_COMMENT_ID: "comment/edit/:id",
  DELIVERYS_ROUTE: "/deliverys",
  DELIVERY_ID_ROUTE: "/delivery/:id",
  EDIT_DELIVERY_ID: "/delivery/edit/:id",
};
